### ISSUE TITLE
example - aspnetcore mvc with framework provided dependency injection

### ISSUE THREAD

**Issue by jamepo** [leosperry/Chroniton#11]
Hi @leosperry 

Great work, nice and lightweight scheduler!
Could you provide an example of registering Chroniton and running it inside aspnetcore mvc project, with the framework provided dependency injection mechanism?

Thanks.

**Comment by leosperry** [comment]
Thank you so much for your interest. I've added a wiki page which should fit your needs.
https://github.com/leosperry/Chroniton/wiki/Example-ASP.NET-Core

**Comment by jamepo** [comment]
@leosperry  appreciate your quick answer and feedback in form of additional wiki page. 

The cause of asking this question was an issue with dbcontext accessed by multiple threads. 
**I will try to get you an example code to reproduce the issue I was facing in next days**, maybe I was doing something stupid or at least wrong ;) ... or I can bring some improvement to Chroniton (?)

The exception message was:

> Additional information: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.

I registerated the Singularity.Instance as a singleton similarly the same way as you did in example code, and the jobs using the IApplicationBuilder.ApplicationServices.GetRequiredServices<T>() (along with dependencies).  

Best regards, James.

**Comment by leosperry** [comment]
To be honest, I have very little experience with ASP.NET Core. However, I may have some insight for you. Each time Chroniton runs a job, it will essentially be running on it's own thread. If you have multiple jobs running, you have to be prepared that they could be doing work simultaneously. So, if they are sharing the same objects, you would run into error messages like the one described above. The 2 easiest ways to fix those kinds of problems is to either make sure that each time a job runs, it has it's own instances of the objects it needs or implement locking mechanisms on the shared objects.

Good Luck!

**Comment by jamepo** [comment]
I am not sure if I properly understand the topic of IOC along with Entity Framework but in my case the key to success was to register db context to be transient along with the jobs being transient too.

Thanks anyway and hope to provide you with code (even might be a working solution :) ) anyway soon.
